app/models.py
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()

class Goal(Base):
    __tablename__ = 'goals'
    id = Column(Integer, primary_key=True)
    goal = Column(String)
    duration = Column(Integer)
    frequency = Column(String)

def init_db():
    engine = create_engine('sqlite:///target.db')
    Base.metadata.create_all(engine)
    return engine

app/__init__.py
from flask import Flask
from .routes import bp


def create_app():
    app = Flask(__name__)
    app.register_blueprint(bp)
    return app

app/routes.py
from flask import Blueprint, request, redirect, render_template,jsonify
from sqlalchemy.orm import sessionmaker
from .models import Goal, init_db

bp = Blueprint('main', __name__)

engine = init_db()
Session = sessionmaker(bind=engine)
session = Session()

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/goals')
def goals():
    goals = session.query(Goal).all()
    goal_list = [{'goal': goal.goal, 'duration': goal.duration, 'frequency': goal.frequency} for goal in goals]
    return render_template('goals.html', goals=goal_list)

@bp.route('/new_goal', methods=['GET', 'POST'])
def new_goal():
    if request.method == 'POST':
        goal = request.form['goal']
        duration = request.form['duration']
        duration_unit = request.form['duration_unit']
        frequency = request.form['frequency']
        if duration_unit == 'hours':
            duration = int(duration) * 60
        duration = int(duration)
        new_goal = Goal(goal=goal, duration=duration, frequency=frequency)
        session.add(new_goal)
        session.commit()
        return redirect('/')
    return render_template('new_goal.html')

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TargetTrail</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles.css') }}"
    />
  </head>
  <body>
    {% include 'navbar.html' %}
    <main>{% block content %}{% endblock %}</main>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/goals.html
{% extends "base.html" %} {% block content %}
<div class="container goal-container">
  <h1 class="d-flex justify-content-center">Goals</h1>
  <ul class="list-group">
    {% for goal in goals %}
    <li class="list-group-item row">
      <span class="col-3">{{goal['goal']}}</span>
      <span class="col-3">{{goal['duration']}}</span>
      <span class="col-3">{{goal['frequency']}}</span>
      <span class="col-3">edit</span>
      <span class="col-3">delete</span>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block content %}
<div class="container d-flex justify-content-center mt-5">
  <div class="card text-center" style="width: 30rem">
    <div class="card-body">
      <h5 class="card-title">Special title treatment</h5>
      <p class="card-text">
        With supporting text below as a natural lead-in to additional content.
      </p>
      <div class="row">
        <div class="col-md-6">
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
        <div class="col-md-6">
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/new_goal.html
{% extends "base.html" %} {% block content %}
<h2>Add New Goal</h2>
<form method="post" action="{{ url_for('main.new_goal') }}">
  <label for="goal">Goal:</label>
  <input type="text" id="goal" name="goal" required />

  <label for="duration">Duration:</label>
  <input type="number" id="duration" name="duration" required />

  <label for="duration_unit">Unit:</label>
  <select id="duration_unit" name="duration_unit" required>
    <option value="minutes">Minutes</option>
    <option value="hours">Hours</option>
  </select>
  <label for="frequency">Frequency</label>
  <select id="frequency" name="frequency" required>
    <option value="daily">Daily</option>
    <option value="weekly">Weekly</option>
    <option value="monthly">Monthly</option>
    <option value="yearly">Yearly</option>
  </select>

  <button type="submit">Add Goal</button>
</form>
{% endblock %}